# Generated by Django 5.0.4 on 2024-05-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_task_project_remove_task_assignee_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
