# Generated by Django 5.0.4 on 2024-06-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_remove_customuser_is_technical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Functional', 'Functional'), ('Tester', 'Tester'), ('Admin', 'Admin')], default='Developer', max_length=10),
        ),
    ]
